import React from 'react';
import { Metadata } from 'next';
import { Breadcrumbs } from '@/components/ui/Breadcrumbs';
import { getBaseUrl } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Terms of Use - File Intelligence',
  description:
    'Read the Terms of Use governing access and utilization of File Intelligence online file inspection utilities.',
  alternates: {
    canonical: `${getBaseUrl()}/terms`,
  },
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      <Breadcrumbs items={[{ label: 'Terms of Use' }]} />

      <header className="mb-10">
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">
          Terms of Use
        </h1>
        <p className="text-xs text-slate-500 dark:text-slate-400 mt-2">
          Effective Date: August 2026 • Version 1.0
        </p>
      </header>

      <div className="space-y-8 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using the File Intelligence website and its associated browser-based inspection tools, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            2. Permitted Use of Tools
          </h2>
          <p>
            File Intelligence provides informational and technical file analysis utilities for personal, educational, commercial, and professional purposes. You agree to use the services in compliance with all applicable laws and regulations.
          </p>
          <p>
            You agree not to:
          </p>
          <ul className="list-disc list-inside space-y-1 text-slate-600 dark:text-slate-400">
            <li>Attempt to interfere with or disrupt the operation of the website.</li>
            <li>Use automated scrapers or bots that degrade website performance for other users.</li>
            <li>Misrepresent the outputs or reports generated by File Intelligence.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            3. Intellectual Property
          </h2>
          <p>
            The software, user interface design, logo, documentation, and technical content of File Intelligence are protected by copyright, trademark, and intellectual property laws. You retain full ownership and all rights to any files you inspect using our tools.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            4. Disclaimer of Warranties
          </h2>
          <p>
            The tools and services are provided on an &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; basis without warranties of any kind, whether express or implied. While we strive for rigorous technical precision, we do not warrant that results will be completely error-free or that all corrupted or malformed file headers will be detected.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
            5. Limitation of Liability
          </h2>
          <p>
            In no event shall File Intelligence or its operators be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the inspection tools or reliance on inspection outputs.
          </p>
        </section>
      </div>
    </div>
  );
}
